import src.palette as palette

# Display
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
FPS = 60
CAPTION = "Ball Battler - Phase 5"

# Physics
GRAVITY = (0, 400)
DT = 1.0 / 60.0
ATTRACTION_FORCE = 2000000.0
KNOCKBACK_IMPULSE = 1000
RECOIL_IMPULSE = 500
WEAPON_CLASH_IMPULSE = 800

# Bullet Time
BULLET_TIME_DURATION = 0.5
BULLET_TIME_SCALE = 0.3
BULLET_TIME_TRIGGER_DISTANCE = 100
HALO_OPACITY = 70

# Collision Types
COLLISION_TYPE_BALL = 1
COLLISION_TYPE_WEAPON = 2
COLLISION_TYPE_OBSTACLE = 3
COLLISION_TYPE_ITEM = 4

# Collision Categories & Masks
CATEGORY_BALL = 0b0001
CATEGORY_WEAPON = 0b0010
CATEGORY_WALL = 0b0100
CATEGORY_OBSTACLE = 0b1000
CATEGORY_ITEM = 0b10000

MASK_BALL = CATEGORY_BALL | CATEGORY_WEAPON | CATEGORY_WALL | CATEGORY_OBSTACLE | CATEGORY_ITEM
MASK_WEAPON = CATEGORY_BALL | CATEGORY_WEAPON

# Arena
WALL_THICKNESS = 10
WALL_ELASTICITY = 1.0
WALL_FRICTION = 0.0
WALL_BOUNCY_ELASTICITY = 1.5

# Obstacles
BUMPER_RADIUS = 25
BUMPER_ELASTICITY = 1.5
BUMPER_SPEED_BOOST = 1.2

# Anomalies
BLACK_HOLE_DURATION = 15.0
BLACK_HOLE_START_DELAY = 5.0
BLACK_HOLE_FORCE = 400000000.0
BLACK_HOLE_RADIUS = 20
BLACK_HOLE_PATH_RADIUS = 150
BLACK_HOLE_SPEED = 0.5 # rad/s
BLACK_HOLE_COLOR = palette.COLOR_VOID
BLACK_HOLE_BORDER_COLOR = palette.COLOR_INDIGO
BLACK_HOLE_OUTER_BORDER_COLOR = palette.COLOR_ORANGE

# Items
ITEM_RADIUS = 15
ITEM_SPAWN_INTERVAL = 10.0 # seconds
ITEM_HEAL_AMOUNT = 30

# Ball Base Stats
BALL_MASS = 10
BALL_RADIUS = 30
BALL_ELASTICITY = 0.99999999999999
BALL_FRICTION = 0.0
BALL_BASE_HP = 120
BALL_BASE_ATTACK = 10
BALL_BASE_SPEED = 500
BALL_BASE_ROTATION_SPEED = 5.0
BALL_FLASH_DURATION = 0.1
BALL_MAX_SPEED = 2000

# Weapon Base
WEAPON_WIDTH = 20
WEAPON_LENGTH = 80

# Colors
COLOR_BG = palette.COLOR_VOID
COLOR_ARENA_FLOOR = palette.COLOR_DARK_GREY
COLOR_TEXT = palette.COLOR_CREAM
COLOR_WALL = palette.COLOR_SILVER
COLOR_OBSTACLE = palette.COLOR_SLATE
COLOR_BUMPER = palette.COLOR_INDIGO
COLOR_ITEM_DEFAULT = palette.COLOR_GREEN
COLOR_ITEM_HEAL = palette.COLOR_GREEN
COLOR_WEAPON_DEFAULT = palette.COLOR_STONE
COLOR_FLASH = palette.COLOR_CREAM
COLOR_BALL_DEFAULT = palette.COLOR_RUST
COLOR_ROGUE = palette.COLOR_VIOLET
COLOR_BERSERKER = palette.COLOR_CORAL
COLOR_PALADIN = palette.COLOR_STEEL
COLOR_MONK = palette.COLOR_ORANGE
COLOR_WARRIOR = palette.COLOR_TEAL
COLOR_RANGER = (34, 139, 34)
COLOR_HIGHLIGHT = palette.COLOR_CREAM
COLOR_SHADOW = palette.COLOR_COCOA

# Rogue Stats
ROGUE_ATTACK = 15
ROGUE_ATTACK_SPEED = 0.5
ROGUE_SPEED = 600
ROGUE_ROTATION_SPEED = 10.0
ROGUE_WEAPON_DIMS = (12, 50) # w, l

# Berserker Stats
BERSERKER_HP = 175
BERSERKER_ATTACK = 20
BERSERKER_ROTATION_SPEED = 5.0
BERSERKER_WEAPON_DIMS = (40, 100) # w, l

# Paladin Stats
PALADIN_HP = 300
PALADIN_ATTACK = 15
PALADIN_ROTATION_SPEED = 6.0
PALADIN_WEAPON_DIMS = (50, 50) # Shield
PALADIN_MAX_SHIELD_WIDTH = 200

# Monk Stats
MONK_HP = 160
MONK_ATTACK = 8
MONK_ATTACK_SPEED = 0.3 # Very fast
MONK_SPEED = 700
MONK_ROTATION_SPEED = 5.0
MONK_WEAPON_DIMS = (30, 30) # Fist (Square)

# Warrior Stats
WARRIOR_HP = 200
WARRIOR_ATTACK = 12
WARRIOR_ROTATION_SPEED = 8.0
WARRIOR_WEAPON_DIMS = (15, 70) # Sword

# Shadow Stats
SHADOW_HP = 150
SHADOW_AOE_RADIUS = 150
SHADOW_BASE_DPS = 5
SHADOW_DPS_SCALING = 3.0

# Ranger Stats
RANGER_ARROW_LIFETIME = 1.5
RANGER_ARROW_MASS = 0.05
RANGER_ARROW_SIZE = (30, 5)
RANGER_ARROW_SPEED = 800
RANGER_TRAP_SIZE = 20
RANGER_TRAP_DAMAGE = 5
RANGER_TRAP_STUN_DURATION = 1.0
RANGER_FIRE_RATE = 0.1
RANGER_TRAP_COOLDOWN = 3.0
RANGER_ATTACK = 12
RANGER_SPEED = 400
RANGER_ROTATION_SPEED = 3.0
